name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt6-base-dev libegl1 cppcheck
          pip install -r requirements.txt
      - name: Static analysis
        run: |
          ./tools/run_cppcheck.sh
          cat cppcheck.log
      - name: Run tests
        run: pytest
