name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-base-dev-tools qt6-multimedia-dev qt6-shadertools-dev libegl1 cppcheck qt6-declarative-dev qt6-tools-dev
          pip install -r requirements.txt
      - name: Static analysis
        run: |
          ./tools/run_cppcheck.sh
          cat cppcheck.log
      - name: Run tests
        run: pytest

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.2'
          modules: 'qtmultimedia qtshadertools'
      - name: Install build tools
        run: |
          choco install make cmake -y
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Build projects
        shell: bash
        run: |
          ./build_projects.sh > build.log 2>&1
      - name: Run tests
        shell: bash
        run: |
          pytest --junitxml tests/windows-test.xml > tests/windows-test.log 2>&1
      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: windows-test-logs
          path: |
            build.log
            tests/windows-test.log
            tests/windows-test.xml
