name: clazy

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  clazy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt and clazy
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-base-dev-tools qt6-multimedia-dev qt6-shadertools-dev clazy bear
      - name: Run clazy
        run: |
          ./tools/run_clazy.sh
          head -n 20 clazy.log || true
      - name: Upload clazy log
        uses: actions/upload-artifact@v4
        with:
          name: clazy-log
          path: clazy.log
