name: cppcheck

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt and cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev cppcheck
      - name: Run cppcheck
        run: |
          ./tools/run_cppcheck.sh
          cat cppcheck.log
      - name: Upload cppcheck log
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-log
          path: cppcheck.log
